[package]
version = "0.1.0"
name = "rab-web"
repository = "https://github.com/itytophile/rab-web"
authors = ["itytophile <imran.tierce@protonmail.com>"]
description = "Rusty Armor Builds - Monster Hunter Rise Armor Set Creation Tool but on the web!"
keywords = ["monster", "hunter", "rise", "armor", "search", "web"]
license = "GPL-3.0"
readme = "./README.md"
edition = "2021"

[dependencies]
sycamore = { git = "https://github.com/sycamore-rs/sycamore", features = [
    "suspense",
] }
rab-core = "0.3"
reqwasm = "0.4"
anyhow = "1"
